"""Populate the database with demo users, cases and appointments.

Usage:  python manage.py seed
All demo accounts use the password "password123".
"""
import datetime

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.utils import timezone

from accounts.models import ClientProfile, LawyerProfile
from appointments.models import Appointment
from cases.models import Case, CaseNote

User = get_user_model()
PASSWORD = 'password123'


class Command(BaseCommand):
    help = 'Seed the database with demo data for the Legal Cases Management System.'

    def handle(self, *args, **options):
        self.stdout.write('Seeding demo data…')

        # --- Admin -----------------------------------------------------------
        admin, created = User.objects.get_or_create(
            username='admin',
            defaults={
                'first_name': 'Olivia', 'last_name': 'Bennett',
                'email': 'admin@legalcms.test', 'role': User.Role.ADMIN,
                'is_staff': True, 'is_superuser': True,
            },
        )
        if created:
            admin.set_password(PASSWORD)
            admin.save()

        # --- Lawyers ---------------------------------------------------------
        lawyers = []
        lawyer_data = [
            ('jcarter', 'James', 'Carter', 'Criminal Law', 'BAR-10231'),
            ('mlopez', 'Maria', 'Lopez', 'Family Law', 'BAR-44872'),
        ]
        for username, first, last, spec, bar in lawyer_data:
            user, created = User.objects.get_or_create(
                username=username,
                defaults={
                    'first_name': first, 'last_name': last,
                    'email': f'{username}@legalcms.test', 'role': User.Role.LAWYER,
                },
            )
            if created:
                user.set_password(PASSWORD)
                user.save()
            profile, _ = LawyerProfile.objects.get_or_create(
                user=user, defaults={'specialization': spec, 'bar_number': bar},
            )
            lawyers.append(profile)

        # --- Clients ---------------------------------------------------------
        clients = []
        client_data = [
            ('rjohnson', 'Robert', 'Johnson', 'Johnson Holdings'),
            ('swilliams', 'Sarah', 'Williams', ''),
        ]
        for username, first, last, company in client_data:
            user, created = User.objects.get_or_create(
                username=username,
                defaults={
                    'first_name': first, 'last_name': last,
                    'email': f'{username}@example.test', 'role': User.Role.CLIENT,
                },
            )
            if created:
                user.set_password(PASSWORD)
                user.save()
            profile, _ = ClientProfile.objects.get_or_create(
                user=user, defaults={'company': company, 'address': '123 Main St'},
            )
            clients.append(profile)

        # --- Cases -----------------------------------------------------------
        today = timezone.now().date()
        case_specs = [
            ('CASE-2026-001', 'Johnson v. Acme Corp', Case.Type.CIVIL,
             Case.Status.IN_PROGRESS, clients[0], lawyers[0]),
            ('CASE-2026-002', 'State v. Williams', Case.Type.CRIMINAL,
             Case.Status.OPEN, clients[1], lawyers[0]),
            ('CASE-2026-003', 'Williams Custody Matter', Case.Type.FAMILY,
             Case.Status.PENDING, clients[1], lawyers[1]),
        ]
        cases = []
        for number, title, ctype, status, client, lawyer in case_specs:
            case, created = Case.objects.get_or_create(
                case_number=number,
                defaults={
                    'title': title, 'case_type': ctype, 'status': status,
                    'client': client, 'lawyer': lawyer,
                    'opened_date': today - datetime.timedelta(days=20),
                    'description': 'Demo case generated by the seed command.',
                },
            )
            if created:
                CaseNote.objects.create(
                    case=case, author=lawyer.user,
                    text='Initial review completed. Awaiting documents.',
                )
            cases.append(case)

        # --- Appointments ----------------------------------------------------
        appt_specs = [
            ('Initial consultation', 2, lawyers[0], clients[0], cases[0]),
            ('Document review', 5, lawyers[0], clients[1], cases[1]),
            ('Mediation session', 8, lawyers[1], clients[1], cases[2]),
        ]
        for title, days_out, lawyer, client, case in appt_specs:
            Appointment.objects.get_or_create(
                title=title, lawyer=lawyer, client=client,
                defaults={
                    'scheduled_for': timezone.now() + datetime.timedelta(days=days_out),
                    'location': 'Firm office, Room A', 'case': case,
                },
            )

        self.stdout.write(self.style.SUCCESS(
            'Done. Log in with:\n'
            '  admin    / password123   (Admin)\n'
            '  jcarter  / password123   (Lawyer)\n'
            '  rjohnson / password123   (Client)'
        ))
